# file: mysql/tasks/configure.yml

- name: install my.cnf
  template:
    src: etc_mysql_my.cnf.j2
    dest: "{{mysql_my_cnf_path}}"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart mysql
