# file: mysql/tasks/install.yml

- name: install mysql packages
  apt:
    pkg: "{{item}}"
    update_cache: yes
    state: present
  when: ansible_os_family == 'Debian'
  with_items: mysql_packages

- name: install mysql packages
  yum:
    pkg: "{{item}}"
    state: present
  when: ansible_os_family == 'RedHat'
  with_items: mysql_packages

- name: ensure mysql is running
  service:
    name: mysql
    state: started
