# file: mysql/tasks/install.yml

- name: install mysql packages
  apt:
    pkg: "{{item}}"
    update_cache: yes
    state: present
  when: ansible_os_family == 'Debian'
  with_items: mysql_packages
  register: mysql_apt_install

- name: install mysql packages
  yum:
    pkg: "{{item}}"
    state: present
  when: ansible_os_family == 'RedHat'
  with_items: mysql_packages
  register: mysql_yum_install

- name: ensure mysql is running
  service:
    name: "{{ mysql_service_name }}"
    state: started
  when: mysql_apt_install|changed or mysql_yum_install|changed
